#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www
#points to your load-balancer IP (lb-01)

subdomain=('www' 'lb-01' 'web-01' 'web-02')
print_info(){
	 printf "The subdomain %s is a " "$2"
	 dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ print $4 }' | tr -d '\n'
	 printf "record and points to "
	 dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ print $5 }' | tr -d '\n'
	 printf "\n"
}

if [ $# -eq 2 ]; then
	print_info "$1" "$2"
else
	for subs in "${subdomain[@]}"
	do
		print_info "$1" "$subs"
	done
fi
