#!/usr/bin/env bash
#Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
service start nginx
sudo rm /var/www/html/index.nginx-debian.html
