#!/usr/bin/env bash
#Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo rm /var/www/html/index.nginx-debian.html
