#!/usr/bin/env bash
#install and configure HAproxy on lb-01 server
apt-get update
apt-get upgrade
sudo apt-get -y install nginx
sudo apt-get -y install haproxy=2.0.\*
sudo sed -i '/Add extra flags here/i ENABLED=1' /etc/default/haproxy
sudo sed -i '/backend/a balance roundrobin' /etc/haproxy/haproxy.cfg
sudo service haproxy start
