#!/usr/bin/env bash
#install and configure HAproxy on lb-01 server
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx
sudo apt-get -y install haproxy=2.0.\*
sudo sed -i '/Add extra flags here/i ENABLED=1' /etc/default/haproxy
sudo sed -i "\$a listen http-incoming\n\tmode http\n\tbind 0.0.0.0:80\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 4325-web-01 54.90.130.172 check\n\tserver 4325-web-02 52.90.163.197 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy start

