#!/usr/bin/env bash
#creates the file containing its PID, display inifite loop, and print "I hate the kill command" when receiving a SIGTERM signal, display "Y U no love me?!" when receiving a SIGINT signal, deletes the file and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid
_term() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}
trap _term SIGTERM
trap _term SIGQUIT
_message(){
	echo "Y U no love me?!"
	exit
}
trap _message SIGINT
while true
do
 	echo "To infinity and beyond"
	sleep 2
done

