#!/usr/bin/env bash
#display inifite loop, and print I am invincible!!! when receiving a SIGTERM signal
_term() {
	echo "I am invincible!!!"
}
trap _term SIGTERM
while true
do
 	echo "To infinity and beyond"
	sleep 2
done
