#!/usr/bin/env bash
# displays Best School 10 times using while loop and if statment
i=1
while [ $i -le 20 ];
do
	if (( i % 15 == 0 ));
	then 
		echo "FizzBuzz"
	elif (( i % 3 == 0 ));
	then
		echo "Fizz"
	elif (( i % 5 == 0));
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
