#!/usr/bin/env bash
# Bash script that displays Best School 10 times using for loop and if statment
i=1
while [ $i -le 10 ];
do
	if [ $i -eq 9 ];
	then 
		echo "Best School"
		echo "Hi"
	else
	echo "Best School"
	fi
	((i++))
done
